<?php

namespace App\Http\Requests\Order;

use App\Models\Order;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class OrderUpdateRequest extends FormRequest
{
    private $statuses;

    protected function prepareForValidation()
    {
        $this->statuses = Order::getStatuses();
    }

    public function rules()
    {
        return [
            'order_status_code' => 'required|string|in_statuses_array'
        ];
    }

    public function withValidator(Validator $validator)
    {
        $validator->addExtension('in_statuses_array', function ($attribute, $value) {
           return in_array($value,$this->statuses);
        });
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
