<?php

namespace App\Http\Requests\Article;

use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\ValidationException;

class ArticleUpdateRequest extends ArticleStoreRequest
{

//    /**
//     * Determine if the user is authorized to make this request.
//     *
//     * @return bool
//     */
//    public function authorize()
//    {
//        return true;
//    }
//
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return parent::rules();
    }
//
//    public function messages()
//    {
//        return parent::messages(); // TODO: Change the autogenerated stub
//    }
//
//    public function attributes()
//    {
//        return parent::attributes(); // TODO: Change the autogenerated stub
//    }
//
//    protected function failedValidation(Validator $validator)
//    {
//        throw (new ValidationException($validator, response()->json([
//            'status' => 'error',
//            'msg' => __('form_request_validation_failed_error'),
//            'error' => $validator->errors()
//        ], 500)));
//    }
//
//    protected function failedAuthorization()
//    {
//        throw new AuthorizationException(__('form_request_authorization_error'), 403);
//    }
}
